[package]
name = "example_impl"
version = "0.1.0"
authors = ["theAzack9 <robin@cavachi.be>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
render = { path = "../render" }

[features]
default=["render/dx12"]